name: GCP - Bot

on:
  push:
    branches: [ "master", "telegram_implementation" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:

    name: 'Deploy to GCP'
    runs-on: ubuntu-latest
    environment: prod
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bot:latest
    
    steps:
      
      # Git checkout
      - name: Checkout
        uses: 'actions/checkout@v3'
        
      # Authenticate with GCP
      - name: AuthGCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Configure Docker GCP
      - name: Configure Docker GCP
        run: gcloud auth configure-docker gcr.io

      # Build Image
      - name: Build Image
        run: docker build -t $IMAGE_NAME src/bot/


      # Configre GCP
      - name: Configure GCP Account
        run:  gcloud config set account ${{ secrets.GOOGLE_EMAIL_ACCOUNT }}

      #Push Image
      - name: Push Image
        run: docker push $IMAGE_NAME

      # Deploy Image
      - name: Deploy Image
        run: gcloud run deploy bot --image $IMAGE_NAME --port 47221 --max-instances 1

  
