name: 'CD Google Functions'

on:
  push:
    branches: [master]


jobs:

  runs-on: ubuntu-latest
  env:
    GOOGLE_DRIVE_KEY : ${{ secrets.GOOGLE_DRIVE_KEY }}

  job_id:
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'function-check-sales-day'
        runtime: 'python39'