name: 'CD - GCP - Cloud Functions'

on:
  push:
    branches: [ "master", "telegram_implementation" ]
  pull_request:
    branches: [ "master" ]


jobs:

  deploy:

    name: 'Deploy to GCP Cloud Functions'
    runs-on: ubuntu-latest
    environment: prod
    env:
      GOOGLE_SERVICE_ACCOUNT_KEY : ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    steps:

      - name: Checkout
        uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

      - id: 'deploy-sales'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          source_dir: 'src/functions/check_sales/'
          entry_point: 'check'
          name: 'function-check-sales-day'
          runtime: 'python39'
          event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
          event_trigger_resource: projects/${{ secrets.GCP_PROJECT_ID }}/topics/${{ secrets.SALES_TOPIC_ID }}
          timeout: '120s'
      
      
      - id: 'deploy-telegram'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          source_dir: 'src/functions/telegram/'
          entry_point: 'check'
          secret_environment_variables: 'TELEGRAM_API_KEY=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/TELEGRAM_API_KEY/versions/latest'
          name: 'function-telegram'
          runtime: 'python39'
          timeout: '120s'