name: 'CD - GCP - Cloud Functions'

on:
  push:
    branches: [ "master", "telegram_implementation" ]
  pull_request:
    branches: [ "master" ]


jobs:

  name: 'Deploy to GCP Cloud Functions'
  runs-on: ubuntu-latest
  environment: prod
  env:
    GOOGLE_SERVICE_ACCOUNT_KEY : ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

  job_id:
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'function-check-sales-day'
        runtime: 'python39'