name: 'CD - GCP - Cloud Functions'

on:
  push:
    branches: [ "master", "telegram_implementation" ]
  pull_request:
    branches: [ "master" ]


jobs:

  deploy:

    name: 'Deploy to GCP Cloud Functions'
    runs-on: ubuntu-latest
    environment: prod
    env:
      GOOGLE_SERVICE_ACCOUNT_KEY : ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    steps:

      - name: Checkout
        uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

      - id: 'deploy-sales'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          source_dir: 'src/functions/check_sales/'
          name: 'function-check-sales-day'
          runtime: 'python39'
      
      - id: 'deploy-telegram'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'function-telegram'
          runtime: 'python39'
          source_dir: 'src/functions/telegram/'